# Generated by Django 3.0.4 on 2020-04-08 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('number', models.IntegerField()),
                ('code', models.IntegerField()),
                ('dateTimeField', models.TextField()),
                ('place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.IntegerField()),
                ('pFact', models.TextField()),
                ('dateBirthday', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('courseAndGroup', models.TextField()),
                ('patronymic', models.TextField()),
                ('numberInsuranceCertificate', models.TextField()),
                ('disability', models.TextField()),
                ('fullStateSupport', models.TextField()),
                ('preferentialCategory', models.TextField()),
                ('nameInstitute', models.TextField()),
                ('namePraepostor', models.TextField()),
                ('numberTravelCard', models.IntegerField()),
                ('addressOfResidence', models.TextField()),
                ('FormOfEducation', models.TextField()),
                ('inProfCom', models.TextField()),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Passport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
