# Generated by Django 3.0.5 on 2020-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200518_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilitygroup',
            name='categories',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='disabilitygroup',
            name='documents',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='pFact',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='textfield1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='textfield2',
            field=models.CharField(max_length=150),
        ),
    ]
