# Generated by Django 3.0.6 on 2020-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200518_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='place',
            new_name='placeOfRegistration',
        ),
        migrations.RemoveField(
            model_name='statement1',
            name='nameInstitute',
        ),
        migrations.AddField(
            model_name='passport',
            name='dateBirthday',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='statement1',
            name='pFact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='pFact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='dateBirthday',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='disability_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='patronymic',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
