# Generated by Django 3.0.4 on 2020-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200524_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='dateBirthday',
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия'),
        ),
    ]
