# Generated by Django 3.0.6 on 2020-05-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20200525_1931'),
        ('document', '0008_auto_20200525_2309'),
    ]

    operations = [
    ]
