# Generated by Django 3.0.4 on 2020-05-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_merge_20200525_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement1',
            name='dateBirthday',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
