# Generated by Django 3.0.4 on 2020-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20200526_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement1',
            name='pFact',
        ),
        migrations.RemoveField(
            model_name='statementprofcom1',
            name='code',
        ),
        migrations.RemoveField(
            model_name='statementprofcom1',
            name='placeOfRegistration',
        ),
        migrations.AddField(
            model_name='statement1',
            name='date_day',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='statement1',
            name='date_month',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='statement1',
            name='date_year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='statement1',
            name='street',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='statementprofcom1',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='apartment',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='disability_group_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='house',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='index',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
