# Generated by Django 3.0.4 on 2020-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20200527_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementprofcom1',
            name='dateTimeField',
        ),
        migrations.AddField(
            model_name='statementprofcom1',
            name='date_day',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='statementprofcom1',
            name='date_month',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='statementprofcom1',
            name='date_year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
