# Generated by Django 3.0.4 on 2020-05-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20200527_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='pFact',
            new_name='street',
        ),
    ]
