# Generated by Django 3.0.4 on 2020-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20200527_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement1',
            old_name='dateTimeField',
            new_name='dateIssue',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='dateTimeField',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='addressOfResidence',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='preferentialCategory',
        ),
        migrations.RemoveField(
            model_name='statement1',
            name='disability_group_text',
        ),
        migrations.AddField(
            model_name='passport',
            name='dateIssue',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Дата Выдачи'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
