# Generated by Django 3.0.4 on 2020-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20200527_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='dateIssue',
        ),
        migrations.AddField(
            model_name='passport',
            name='date_day',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AddField(
            model_name='passport',
            name='date_month',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AddField(
            model_name='passport',
            name='date_year',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Год выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='course',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='nameHeadman',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя старосты'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='nameInstitute',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название института'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='dateBirthday',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='placeOfRegistration',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место регистрации'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='FormOfEducation',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Форма Обучения'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='INN',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='apartment',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='disability',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Группа инвалидности'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='fullStateSupport',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Есть ли полное гос. обеспечение'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='house',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер Дома'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='inProfCom',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Состоите ли вы в профкоме'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='index',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='numberInsuranceCertificate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер страхового свидетельства'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='numberTravelCard',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер проездной карты'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Сотовый Телефон'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='surname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='INN',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='apartment',
            field=models.IntegerField(blank=True, max_length=7, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='course',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='dateBirthday',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Страховое свидетельство'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='dateIssue',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='date_day',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='date_month',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='date_year',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Год выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='disability_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страховое свидетельство'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='fullStateSupport',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, null=True, verbose_name='ПОлное гос.обеспечение'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='house',
            field=models.IntegerField(blank=True, max_length=7, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='index',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='nameHeadman',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя старосты'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='name_institute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название института'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='numberInsuranceCertificate',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Страховое свидетельство'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='number_of_statement',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Номер заявления'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='patronymic',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Паспорт выдан'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='street',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='surname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='textfield1',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='Просьба'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='textfield2',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='INN',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='apartment',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='dateBirthday',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='date_day',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='date_month',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='date_year',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='house',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='name_institute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название института'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='patronymic',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Паспорт выдан'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='surname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='textfield1',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='Просьба'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='textfield2',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='Приложение'),
        ),
    ]
