# Generated by Django 3.0.4 on 2020-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20200527_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='nameHeadman',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО старосты'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='nameHeadman',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='фИО старосты'),
        ),
    ]
