# Generated by Django 3.0.6 on 2020-05-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_auto_20200527_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement1',
            name='dateIssue',
        ),
    ]
