# Generated by Django 3.0.6 on 2020-07-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_auto_20200709_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number_passport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_issue_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_issue_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_issue_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='INN',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='number_insurance_certificate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер страхового свидетельства'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='number_travel_card',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер проездной карты'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сотовый Телефон'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='INN',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='number_insurance_certificate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Страховое свидетельство'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='number_of_statement',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=None, max_length=1, null=True, verbose_name='Номер заявления'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='number_passport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='passport_issue_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='passport_issue_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='passport_issue_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='INN',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='number_passport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='passport_issue_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='passport_issue_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='passport_issue_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выдачи Паспорта'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='statementprofcom1',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия'),
        ),
    ]
