# Generated by Django 3.0.8 on 2020-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20200714_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='form_education',
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='course',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='statement1',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, null=True, verbose_name='Курс'),
        ),
    ]
